[package]
name = "camera"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
image = "0.25.6"
imageproc = "0.25.0"
libcamera = "0.4.0"
libcamera-sys = "0.4.0"
rerun = "0.25.1"

[profile.dev]
incremental = true

[profile.release]
incremental = true