[build]
default-target = "aarch64-unknown-linux-gnu"

[build.env]
passthrough = ["RUST_DEBUG"]

[target.aarch64-unknown-linux-gnu]
dockerfile.file = "docker/Dockerfile.aarch64"
dockerfile.context = "docker"