#!/bin/bash

# Penser à :
# Pour libcamera :
#    sudo apt-get install libclang-dev
#    script de github libcamera-rs pour installer libcamera 0.3.2 # https://github.com/lit-robotics/libcamera-rs/issues/56
# Pour opencv :
#    sudo apt-get install libopencv-dev
#    sudo apt install llvm-dev libclang-dev clang

# Penser v2
# Pour libcamera :
#     sudo apt install libcamera0.4
#     sudo apt install libcamera-dev
#     sudo apt-get install libclang-dev




ip_addr=192.168.1.35

echo "transferring file..."

rsync -av --exclude='target' ./** robot@$ip_addr:/home/robot/prog/cam/

if [ $? -eq 0 ]; then
    echo "done."
else
    echo "an error occurred when transferring files."
    exit 1
fi

ssh robot@$ip_addr 'cd /home/robot/prog/cam; export PATH="/home/robot/.cargo/bin:$PATH"; cargo run --verbose'

if [ $? -eq 0 ]; then
    echo "started."
else
    echo "an error occurred during compilation."
    exit 1
fi

pscp -r . robot@10.87.216.195:/home/robot/prog/motors